# Use the README file as a reference to customize settings.

Interval:
  fields:
    default: resort, init, finish
    list: resort, init, finish
    form: resort, init, finish
    options:
      selectors: resorts
  relationships: resort, books
  options:
    only_user_items: false