# Use the README file as a reference to customize settings.

Offer:
  fields:
    default: resort, service_extra, enable, hduration, hcost
    form: service_extra, enable, hduration, hcost
    options:
      selectors: resorts, service_extras
  relationships: resort, service_extra
  application: Application
