# Use the README file as a reference to customize settings.

Resort:
  fields:
    default: name, store
    list: name, store
    form: name
    options:
      selectors: stores
  relationships: store, intervals, offers
  application: Application
  options:
    only_user_items: false