# Use the README file as a reference to customize settings.

ServiceExtra:
  fields:
    default: name, lasting, cost, store
    form: name, lasting, cost
    options:
      selectors: stores
  relationships: stores, offers
  application: Application
